baseurl = "https://cfazilleau.netlify.app/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 15
enableRobotsTXT = true

#https://github.com/panr/hugo-theme-hello-friend/
#https://github.com/tomik23/zooom.js/

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4
  # Show reading time in minutes for posts
  showReadingTime = false
  # google search console verification code
  googleVerificationCode = "cCFejK_e3MFSd-nynTCFKkawPutzEJYCJ4Y3hmLg38w"
  # google analytics code
  googleAnalyticsCode = "UA-146410600-1"

  [params.social.github]
    name = "github"
    url = "https://github.com/cfazilleau"
  #[params.social.gitlab]
  #  name = "gitlab"
  #  url = "test"
  [params.social.itchio]
    name = "itchio"
    url = "https://cfazilleau.itch.io/"
  [params.social.linkedin]
    name = "linkedin"
    url = "https://www.linkedin.com/in/clement-f"
  [params.social.mail]
    name = "mail"
    url = "mailto:faz.cle@gmail.com"

[languages]
  [languages.en]
    languageName = "English" 
    contentDir = "content/en"
    title = "Clément Fazilleau"
    subtitle = "A simple blog for my projects"
    keywords = "Clement Fazilleau, Clement, Fazilleau, Blog, Developper, Site, Website, Projects, Code, Games, Programming"
    copyright = "Clément Fazilleau"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "CFazilleau"
      logoHomeLink = "/"

      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Latest posts"
        url = "/posts/"

      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/categories/project/"

  [languages.fr]
    languageName = "Francais"
    contentDir = "content/fr"
    title = "Clément Fazilleau"
    subtitle = "Un simple blog pour mes projets"
    keywords = "Clement Fazilleau, Clement, Fazilleau, Blog, Developpeur, Site, Website, Projets, Code, Jeux Video, Jeu Video, Programmation"
    copyright = "Clément Fazilleau"
    menuMore = "Voir plus"
    writtenBy = "Rédigé par"
    readMore = "Lire la suite"
    readOtherPosts = "Lire d'autres posts"
    newerPosts = "Posts plus récents"
    olderPosts = "Posts plus anciens"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.fr.params.logo]
      logoText = "CFazilleau"
      logoHomeLink = "/fr/"

      [[languages.fr.menu.main]]
        identifier = "posts"
        name = "Derniers posts"
        url = "/fr/posts/"

      [[languages.fr.menu.main]]
        identifier = "projects"
        name = "Projets"
        url = "/fr/categories/project/"