baseurl = ""
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

#https://github.com/panr/hugo-theme-hello-friend/

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # Show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "CFazilleau"
    subtitle = "A simple blog for my projects"
    keywords = ""
    copyright = "Clément Fazilleau"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "CFazilleau"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "latest"
        name = "Latest Posts"
        url = "/post/"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/about/"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/categories/project/"